let gallery = new ImageGallery([
  new GalleryImage('../images/joseph.png',
    'Joseph Campbell smiling.',
    '"It is by going down into the abyss that we recover the treasures of life. Where you stumble, there lies your treasure."',
    'Joseph Campbell\'s theory on story structure lives a double life as spiritual theory for many people. This might explain the apparent effectiveness of structuring your story by conflicts and their various resolutions -- it resonates on a fundamental level.'),
  new GalleryImage('../images/mckee.png',
    'Robert McKee with his finger pressed against his cheek, presumably thinking.',
    '"Anxious, inexperienced writers obey rules. Rebellious, unschooled writers break rules. Artists master the form."',
    'Quotes like these are often taken out of context online and used as \'motivational\' material. In context, in his book \'Story\', McKee is discussing the differences between rules and principles, and encouraging practiced handling of the storytelling form -- not nearly as elitist as the quote might appear.'),
  new GalleryImage('../images/harmon.png',
    'Dan Harmon on a stage at Comic Con.',
    'If you have writer\'s block, switch from the goal of writing something good, to the goal of proving how bad you are.',
    'Dan Harmon takes a blunt and honest approach to writing advice, and writing in general. You might find his approach more reasonable and helpful than the standard \'motivational\' content you find online.'),
  new GalleryImage('../images/kaufman.png',
    'Charlie Kaufman on stage at Fantastic Fest.',
    '"Everything I\'ve written is personal -- it\'s the only way I know how to write."',
    'Charlie Kaufman takes a literary approach to screenwriting. He sees writing as an intimate, emotional process, a story in and of itself. This reflects in the metatextual nature of his stories -- he often writes stories about the process of telling the story itself.'),
  new GalleryImage('../images/ishiguro.png',
    'A face profile of Kazuo Ishiguro wearing a black suit and a beige earpiece at an event.',
    '"As a writer, I\'m more interested in what people tell themselves happened rather than what actually happened."',
    'Kazuo Ishiguro consistently writes stories about how people engage with their memories. This explains why he sees perception as a fundamental aspect of his writing practice. You might diverge from Ishiguro -- maybe stories for you are about the impacts people\'s actions have rather than the intention behind the actions themselves.'),
  new GalleryImage('../images/george.png',
    'A blurry picture of George Pólya smiling.',
    '"If you cannot solve the proposed problem try to solve first some related problem."',
    'George Pólya\'s book \'How to Solve it\' focuses on solving problems in mathematics, but many of its principles can be translated to storytelling. You might find it easier to write stories once you hone your critical thinking skills with resources like these.'),
  new GalleryImage('../images/koh.png',
    'Julie Koh with her head in her hand.',
    '"I start with a premise or an idea that intrigues me, and the techniques I use to communicate that are just frills on the mannequin."',
    'Julie Koh writes expertly and precisely -- her sentences are perfect and constrained. This may be a result of her practical approach to writing, as demonstrated in this quote. Techniques to her are tools -- they are a means to make her ends (her ideas) more digestible.'),
  new GalleryImage('../images/wright.png',
    'Alexis Wright smiling with glasses in hand.',
    '"My role as a novelist is to explore ideas and imagination, and hopefully that will inspire people from my world to continue dreaming and to believe in dreams."',
    'Alexis Wright writes to provoke imagination on an everyday level, but also on a political level. She wants her people (Aboriginal people) to be inspired to dream of a world with self-determination. You might consider a similar political dimension in your own writing.'),
  new GalleryImage('../images/king.png',
    'Stephen King looking off to the side, wearing glasses.',
    '"Amateurs sit and wait for inspiration, the rest of us just get up and go to work."',
    'Stephen King wrote a book called \'On Writing\', from which lines are often shared around the Internet as motivational material. Quotes like these can certainly be motivational, but they can also invite a couple nasty mindsets: gatekeeping (who do we get to call an amateur?) and an unhealthy relationship with productivity (are you really working hard enough?).'),
  new GalleryImage('../images/coyote.png',
    'Ivan Coyote staring at the viewer.',
    '"I am writing myself down so I can find myself later."',
    'Ivan Coyote often writes about their lived experience as a nonbinary person. They see their writing partly as a form of self-discovery -- both a reminder of who they are (a kind of label), and a process for them to discover who they are. How might you discover yourself through the storytelling process?')
]);
