let gallery = new ImageGallery([
  new GalleryImage('./images/w3c-validation/html/1-index.PNG', 'W3C code validation screenshot', 'HTML - Index', ''),
  new GalleryImage('./images/w3c-validation/html/2-sitemap.PNG', 'W3C code validation screenshot', 'HTML - Site Map', ''),
  new GalleryImage('./images/w3c-validation/html/3-sourcelog.PNG', 'W3C code validation screenshot', 'HTML - Source Log', ''),
  new GalleryImage('./images/w3c-validation/html/4-about.PNG', 'W3C code validation screenshot', 'HTML - About', ''),
  new GalleryImage('./images/w3c-validation/html/5-feedback.PNG', 'W3C code validation screenshot', 'HTML - Feedback', ''),
  new GalleryImage('./images/w3c-validation/html/6-reflection.PNG', 'W3C code validation screenshot', 'HTML - Reflection', ''),
  new GalleryImage('./images/w3c-validation/html/7-advice.PNG', 'W3C code validation screenshot', 'HTML - Good Writing Advice is a Tool', ''),
  new GalleryImage('./images/w3c-validation/html/8-structure.PNG', 'W3C code validation screenshot', 'HTML - How to Structure a Story', ''),
  new GalleryImage('./images/w3c-validation/html/9-mckee.PNG', 'W3C code validation screenshot', 'HTML - Defining Your Story with the McKee Triangle', ''),
  new GalleryImage('./images/w3c-validation/html/10-abyssrebirth.PNG', 'W3C code validation screenshot', 'HTML - Example Structure: Abyss & Rebirth', ''),
  new GalleryImage('./images/w3c-validation/html/11-adapt.PNG', 'W3C code validation screenshot', 'HTML - Example Structure: Adapt', ''),
  new GalleryImage('./images/w3c-validation/html/12-ordinaryworld.PNG', 'W3C code validation screenshot', 'HTML - Example Structure: Ordinary World', ''),
  new GalleryImage('./images/w3c-validation/html/13-returnnewworld.PNG', 'W3C code validation screenshot', 'HTML - Example Structure: Return and New World', ''),
  new GalleryImage('./images/w3c-validation/html/14-thecall.PNG', 'W3C code validation screenshot', 'HTML - Example Structure: The Call', ''),
  new GalleryImage('./images/w3c-validation/html/15-trials.PNG', 'W3C code validation screenshot', 'HTML - Example Structure: Trials', ''),
  new GalleryImage('./images/w3c-validation/css/1-article.PNG', 'W3C code validation screenshot', 'CSS - Article', ''),
  new GalleryImage('./images/w3c-validation/css/2-colours.PNG', 'W3C code validation screenshot', 'CSS - Colours', ''),
  new GalleryImage('./images/w3c-validation/css/3-colours-alt.PNG', 'W3C code validation screenshot', 'CSS - Colours (Style Swap)', ''),
  new GalleryImage('./images/w3c-validation/css/4-feedback.PNG', 'W3C code validation screenshot', 'CSS - Feedback', ''),
  new GalleryImage('./images/w3c-validation/css/5-hero.PNG', 'W3C code validation screenshot', 'CSS - How to Structure a Story', ''),
  new GalleryImage('./images/w3c-validation/css/6-imagegallery.PNG', 'W3C code validation screenshot', 'CSS - Image Galleries', ''),
  new GalleryImage('./images/w3c-validation/css/7-index.PNG', 'W3C code validation screenshot', 'CSS - Index', 'This is an error related to my use of the linear-gradient() function. I consulted the specification for the linear-gradient() function, and there does not appear to be anything preventing me from using a space in the function invocation. Therefore, I think this is an error with W3C\'s validation system.'),
  new GalleryImage('./images/w3c-validation/css/8-index-alt.PNG', 'W3C code validation screenshot', 'CSS - Index (Style Swap)', ''),
  new GalleryImage('./images/w3c-validation/css/9-main.PNG', 'W3C code validation screenshot', 'CSS - All pages', ''),
  new GalleryImage('./images/w3c-validation/css/10-main-alt.PNG', 'W3C code validation screenshot', 'CSS - All pages (Style Swap)', ''),
  new GalleryImage('./images/w3c-validation/css/11-mckee.PNG', 'W3C code validation screenshot', 'CSS - Defining Your Story with the McKee Triangle', ''),
  new GalleryImage('./images/w3c-validation/css/12-sitemap.PNG', 'W3C code validation screenshot', 'CSS - Site map', ''),
  new GalleryImage('./images/w3c-validation/css/13-sourcelog.PNG', 'W3C code validation screenshot', 'CSS - Source log', ''),
  new GalleryImage('./images/w3c-validation/css/14-quotes.PNG', 'W3C code validation screenshot', 'CSS - Quotes', '')
]);
